version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: task_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: taskdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: task_keycloak
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  api:
    build: ../../apps/api
    container_name: task_api
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://admin:admin@postgres:5432/taskdb
      KEYCLOAK_URL: http://keycloak:8080
      KEYCLOAK_REALM: task-manager
      KEYCLOAK_CLIENT_ID: backend
    depends_on:
      - postgres
      - keycloak

volumes:
  postgres_data: